// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NatureAPI;

#nullable disable

namespace NatureAPI.Migrations
{
    [DbContext(typeof(NatureDbContext))]
    [Migration("20251120224322_prueba deploy")]
    partial class pruebadeploy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NatureAPI.Models.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Baños"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Estacionamiento"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mirador"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Zona de Picnic"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Área de Camping"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Señalización"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sendero Guiado"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Restaurante"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Área de Observación"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Centro de Visitantes"
                        });
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlaceId = 1,
                            Url = "https://www.gob.mx/cms/uploads/article/main_image/27513/blog_izta_popo.jpg"
                        },
                        new
                        {
                            Id = 2,
                            PlaceId = 2,
                            Url = "https://escapadas.mexicodesconocido.com.mx/wp-content/uploads/2020/10/Cascada-Cola-de-Caballo-XL-scaled.jpeg"
                        },
                        new
                        {
                            Id = 3,
                            PlaceId = 3,
                            Url = "https://www.civitatis.com/f/mexico/monterrey/galeria/senderismo-cerro-silla4.jpg"
                        },
                        new
                        {
                            Id = 4,
                            PlaceId = 4,
                            Url = "https://visitmexico.com/media/usercontent/6886d984e4344-chipinque-3_gmxdot_jpg"
                        },
                        new
                        {
                            Id = 5,
                            PlaceId = 5,
                            Url = "https://www.gob.mx/cms/uploads/image/file/247330/Basaseachi__foto_Teresita_Lasso__18_.JPG"
                        },
                        new
                        {
                            Id = 6,
                            PlaceId = 6,
                            Url = "https://www.zacatecastravel.com/img/lugares/miradorlabufa_grande.jpg"
                        },
                        new
                        {
                            Id = 7,
                            PlaceId = 7,
                            Url = "https://www.gob.mx/cms/uploads/article/main_image/28051/blog_PNCM.jpg"
                        },
                        new
                        {
                            Id = 8,
                            PlaceId = 8,
                            Url = "https://noro.mx/wp-content/uploads/2024/08/Cascada-Piedra-Volada-renace-en-la-Sierra-Tarahumara.jpg"
                        },
                        new
                        {
                            Id = 9,
                            PlaceId = 9,
                            Url = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Mirador_de_la_Pe%C3%B1a.jpg/1200px-Mirador_de_la_Pe%C3%B1a.jpg"
                        },
                        new
                        {
                            Id = 10,
                            PlaceId = 10,
                            Url = "https://cdn.mexicodestinos.com/lugares/nevado-de-toluca-galeria.jpg"
                        });
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Accessible")
                        .HasColumnType("bit");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElevationMeters")
                        .HasColumnType("int");

                    b.Property<double>("EntryFee")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accessible = true,
                            Category = "Parque",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Área natural protegida que rodea los volcanes Popocatépetl e Iztaccíhuatl, segunda y tercera montañas más altas de México. Cuenta con bosques de coníferas, praderas alpinas y senderos de alta montaña.",
                            ElevationMeters = 3600,
                            EntryFee = 45.0,
                            Latitude = 19.179099999999998,
                            Longitude = -98.627700000000004,
                            Name = "Parque Nacional Iztaccíhuatl-Popocatépetl",
                            OpeningHours = "07:00-16:00"
                        },
                        new
                        {
                            Id = 2,
                            Accessible = true,
                            Category = "Cascada",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Impresionante cascada de 25 metros de altura ubicada en el Parque Ecológico Cola de Caballo. El agua cae formando una silueta que asemeja la cola de un caballo.",
                            ElevationMeters = 620,
                            EntryFee = 50.0,
                            Latitude = 25.4665,
                            Longitude = -100.1365,
                            Name = "Cascada Cola de Caballo",
                            OpeningHours = "09:00-17:00"
                        },
                        new
                        {
                            Id = 3,
                            Accessible = true,
                            Category = "Mirador",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Icónico cerro de Monterrey con forma de silla de montar. El mirador ofrece vistas panorámicas de toda el área metropolitana. Incluye antiguas instalaciones del teleférico.",
                            ElevationMeters = 1820,
                            EntryFee = 0.0,
                            Latitude = 25.630299999999998,
                            Longitude = -100.2347,
                            Name = "Mirador del Cerro de la Silla",
                            OpeningHours = "06:00-18:00"
                        },
                        new
                        {
                            Id = 4,
                            Accessible = true,
                            Category = "Parque",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reserva natural privada en la Sierra Madre Oriental con 1,791 hectáreas de bosque. Ofrece más de 60 km de senderos señalizados, miradores y áreas de picnic.",
                            ElevationMeters = 2100,
                            EntryFee = 90.0,
                            Latitude = 25.6187,
                            Longitude = -100.36279999999999,
                            Name = "Parque Ecológico Chipinque",
                            OpeningHours = "05:30-19:30"
                        },
                        new
                        {
                            Id = 5,
                            Accessible = false,
                            Category = "Cascada",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "La cascada permanente más alta de México con 246 metros de caída libre. Ubicada en la Sierra Madre Occidental, rodeada de bosques de pino y encino.",
                            ElevationMeters = 1900,
                            EntryFee = 35.0,
                            Latitude = 28.191700000000001,
                            Longitude = -108.2153,
                            Name = "Cascada de Basaseachi",
                            OpeningHours = "08:00-17:00"
                        },
                        new
                        {
                            Id = 6,
                            Accessible = true,
                            Category = "Mirador",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Emblemático cerro de Zacatecas a 2,610 metros sobre el nivel del mar. Sitio histórico de la Toma de Zacatecas y patrimonio de la UNESCO. Ofrece vistas panorámicas de 360 grados.",
                            ElevationMeters = 2610,
                            EntryFee = 0.0,
                            Latitude = 22.778700000000001,
                            Longitude = -102.568,
                            Name = "Mirador Cerro de la Bufa",
                            OpeningHours = "09:00-18:00"
                        },
                        new
                        {
                            Id = 7,
                            Accessible = true,
                            Category = "Parque",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Extenso parque nacional en la Sierra Madre Oriental que abarca 177,395 hectáreas. Incluye cañones profundos, cascadas y rica biodiversidad.",
                            ElevationMeters = 2240,
                            EntryFee = 0.0,
                            Latitude = 25.583300000000001,
                            Longitude = -100.2167,
                            Name = "Parque Nacional Cumbres de Monterrey",
                            OpeningHours = "24 horas"
                        },
                        new
                        {
                            Id = 8,
                            Accessible = false,
                            Category = "Cascada",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "La cascada más alta de México con 453 metros de caída libre. Ubicada en el mismo parque nacional que Basaseachi, solo lleva agua en temporada de lluvias.",
                            ElevationMeters = 1850,
                            EntryFee = 35.0,
                            Latitude = 28.175000000000001,
                            Longitude = -108.20829999999999,
                            Name = "Cascada de Piedra Volada",
                            OpeningHours = "08:00-17:00"
                        },
                        new
                        {
                            Id = 9,
                            Accessible = true,
                            Category = "Mirador",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mirador junto al tercer monolito más grande del mundo. Ubicado en el Pueblo Mágico de Bernal, Querétaro, ofrece vistas espectaculares del valle.",
                            ElevationMeters = 2500,
                            EntryFee = 0.0,
                            Latitude = 20.744700000000002,
                            Longitude = -99.944400000000002,
                            Name = "Mirador La Peña de Bernal",
                            OpeningHours = "06:00-19:00"
                        },
                        new
                        {
                            Id = 10,
                            Accessible = true,
                            Category = "Parque",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Parque nacional que rodea el volcán Nevado de Toluca (4,680 msnm). Cuenta con dos lagunas cratéricas: Laguna del Sol y Laguna de la Luna.",
                            ElevationMeters = 4200,
                            EntryFee = 65.0,
                            Latitude = 19.108499999999999,
                            Longitude = -99.757300000000001,
                            Name = "Parque Nacional Nevado de Toluca",
                            OpeningHours = "06:00-17:00"
                        });
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.PlaceAmenity", b =>
                {
                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.HasKey("PlaceId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("PlaceAmenities");

                    b.HasData(
                        new
                        {
                            PlaceId = 1,
                            AmenityId = 1
                        },
                        new
                        {
                            PlaceId = 1,
                            AmenityId = 2
                        },
                        new
                        {
                            PlaceId = 1,
                            AmenityId = 4
                        },
                        new
                        {
                            PlaceId = 1,
                            AmenityId = 10
                        },
                        new
                        {
                            PlaceId = 2,
                            AmenityId = 1
                        },
                        new
                        {
                            PlaceId = 2,
                            AmenityId = 2
                        },
                        new
                        {
                            PlaceId = 2,
                            AmenityId = 4
                        },
                        new
                        {
                            PlaceId = 2,
                            AmenityId = 8
                        },
                        new
                        {
                            PlaceId = 3,
                            AmenityId = 3
                        },
                        new
                        {
                            PlaceId = 3,
                            AmenityId = 6
                        },
                        new
                        {
                            PlaceId = 4,
                            AmenityId = 1
                        },
                        new
                        {
                            PlaceId = 4,
                            AmenityId = 2
                        },
                        new
                        {
                            PlaceId = 4,
                            AmenityId = 3
                        },
                        new
                        {
                            PlaceId = 4,
                            AmenityId = 6
                        },
                        new
                        {
                            PlaceId = 4,
                            AmenityId = 8
                        },
                        new
                        {
                            PlaceId = 5,
                            AmenityId = 2
                        },
                        new
                        {
                            PlaceId = 5,
                            AmenityId = 3
                        },
                        new
                        {
                            PlaceId = 5,
                            AmenityId = 5
                        },
                        new
                        {
                            PlaceId = 6,
                            AmenityId = 3
                        },
                        new
                        {
                            PlaceId = 6,
                            AmenityId = 8
                        },
                        new
                        {
                            PlaceId = 7,
                            AmenityId = 1
                        },
                        new
                        {
                            PlaceId = 7,
                            AmenityId = 5
                        },
                        new
                        {
                            PlaceId = 7,
                            AmenityId = 6
                        },
                        new
                        {
                            PlaceId = 8,
                            AmenityId = 3
                        },
                        new
                        {
                            PlaceId = 9,
                            AmenityId = 3
                        },
                        new
                        {
                            PlaceId = 9,
                            AmenityId = 8
                        },
                        new
                        {
                            PlaceId = 10,
                            AmenityId = 2
                        },
                        new
                        {
                            PlaceId = 10,
                            AmenityId = 3
                        },
                        new
                        {
                            PlaceId = 10,
                            AmenityId = 10
                        });
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Trail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("EstimatedTimeMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsLoop")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Trails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Difficulty = "Alta",
                            DistanceKm = 8.5,
                            EstimatedTimeMinutes = 240,
                            IsLoop = false,
                            Name = "Sendero Paso de Cortés",
                            Path = "[[19.1791, -98.6277], [19.1850, -98.6200], [19.1900, -98.6150]]",
                            PlaceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Difficulty = "Media",
                            DistanceKm = 3.5,
                            EstimatedTimeMinutes = 90,
                            IsLoop = false,
                            Name = "Mirador La Joya",
                            Path = "[[19.1750, -98.6300], [19.1780, -98.6250], [19.1800, -98.6220]]",
                            PlaceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Difficulty = "Baja",
                            DistanceKm = 0.59999999999999998,
                            EstimatedTimeMinutes = 30,
                            IsLoop = false,
                            Name = "Sendero a la Cascada",
                            Path = "[[25.4700, -100.1400], [25.4680, -100.1380], [25.4665, -100.1365]]",
                            PlaceId = 2
                        },
                        new
                        {
                            Id = 4,
                            Difficulty = "Media",
                            DistanceKm = 4.2999999999999998,
                            EstimatedTimeMinutes = 150,
                            IsLoop = false,
                            Name = "Ascenso Pico Antena",
                            Path = "[[25.6200, -100.2400], [25.6250, -100.2370], [25.6303, -100.2347]]",
                            PlaceId = 3
                        },
                        new
                        {
                            Id = 5,
                            Difficulty = "Media",
                            DistanceKm = 5.7999999999999998,
                            EstimatedTimeMinutes = 120,
                            IsLoop = true,
                            Name = "Sendero del Coatí",
                            Path = "[[25.6150, -100.3650], [25.6200, -100.3600], [25.6250, -100.3580], [25.6150, -100.3650]]",
                            PlaceId = 4
                        },
                        new
                        {
                            Id = 6,
                            Difficulty = "Alta",
                            DistanceKm = 2.0,
                            EstimatedTimeMinutes = 90,
                            IsLoop = false,
                            Name = "Descenso a la Base de la Cascada",
                            Path = "[[28.1950, -108.2180], [28.1930, -108.2165], [28.1917, -108.2153]]",
                            PlaceId = 5
                        },
                        new
                        {
                            Id = 7,
                            Difficulty = "Media",
                            DistanceKm = 2.5,
                            EstimatedTimeMinutes = 60,
                            IsLoop = false,
                            Name = "Ruta Histórica La Bufa",
                            Path = "[[22.7720, -102.5720], [22.7750, -102.5700], [22.7787, -102.5680]]",
                            PlaceId = 6
                        },
                        new
                        {
                            Id = 8,
                            Difficulty = "Media",
                            DistanceKm = 4.2000000000000002,
                            EstimatedTimeMinutes = 110,
                            IsLoop = false,
                            Name = "Sendero Cañón de la Huasteca",
                            Path = "[[25.5900, -100.2200], [25.5850, -100.2150], [25.5800, -100.2100]]",
                            PlaceId = 7
                        },
                        new
                        {
                            Id = 9,
                            Difficulty = "Alta",
                            DistanceKm = 3.7999999999999998,
                            EstimatedTimeMinutes = 140,
                            IsLoop = false,
                            Name = "Mirador Piedra Volada",
                            Path = "[[28.1800, -108.2120], [28.1770, -108.2100], [28.1750, -108.2083]]",
                            PlaceId = 8
                        },
                        new
                        {
                            Id = 10,
                            Difficulty = "Media",
                            DistanceKm = 1.5,
                            EstimatedTimeMinutes = 90,
                            IsLoop = false,
                            Name = "Ascenso a la Peña",
                            Path = "[[20.7400, -99.9480], [20.7420, -99.9460], [20.7447, -99.9444]]",
                            PlaceId = 9
                        });
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Photo", b =>
                {
                    b.HasOne("NatureAPI.Models.Entities.Place", "Place")
                        .WithMany("Photos")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.PlaceAmenity", b =>
                {
                    b.HasOne("NatureAPI.Models.Entities.Amenity", "Amenity")
                        .WithMany("PlaceAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureAPI.Models.Entities.Place", "Place")
                        .WithMany("PlaceAmenities")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Review", b =>
                {
                    b.HasOne("NatureAPI.Models.Entities.Place", "Place")
                        .WithMany("Reviews")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Trail", b =>
                {
                    b.HasOne("NatureAPI.Models.Entities.Place", "Place")
                        .WithMany("Trails")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Amenity", b =>
                {
                    b.Navigation("PlaceAmenities");
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Place", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("PlaceAmenities");

                    b.Navigation("Reviews");

                    b.Navigation("Trails");
                });
#pragma warning restore 612, 618
        }
    }
}
